### ISSUE TITLE
PCB

### ISSUE THREAD

**Issue by sspencer10** [H4ckd4ddy/fix-sentry-safe#1]
The board you are holding in your hand in the README says version 2.1. What's changed on that board from version 2.0 found in the PCB directory?

**Comment by H4ckd4ddy** [comment]
Hi,
Well done, I wondered if anyone would notice.
On 2.0, main microcontroller is maintained in deep sleep, and wake up when a signal is received from keypad (green wire)
On 2.1, I tried to add a PNP transistor between green wire and microcontroller wake up pin, to reduce even more sleep power consumption.
But it's useless and do not work properly. As you can see on the picture, at the bottom of PCB, the PNP transistor is not even assembled.
Best regards

**Comment by sspencer10** [comment]
Ok, thanks for the explanation. You can mark as closed. Nice work on this project. Very interesting!
